### ISSUE TITLE
[Stocks] Attempting to buy some stocks returns None values

### ISSUE THREAD

**Issue by MeatyChunks** [Flame442/FlameCogs#64]
Hey, just installed this cog and noticed a user trying to buy the BTC stock but it was throwing back some errors due to None values.

```py
Traceback (most recent call last):
  File "site-packages\discord\ext\commands\core.py", line 85, in wrapped
    ret = await coro(*args, **kwargs)
  File "stocks\stocks.py", line 38, in buy
    stock_data = await self._get_stock_data([name])
  File "stocks\stocks.py", line 223, in _get_stock_data
    stock = {
  File "stocks\stocks.py", line 225, in <dictcomp>
    'price': max(1, int(x['last'] * 100)),
TypeError: unsupported operand type(s) for *: 'NoneType' and 'int'
```
Here is the data I was getting back if it helps:
```
{'quotes': {'quote': {'symbol': 'BTC', 'description': None, 'exch': 'P', 'type': 'stock', 'last': None, 'change': None, 'volume': 0, 'open': None, 'high': None, 'low': None, 'close': None, 'bid': None, 'ask': None, 'change_percentage': None, 'average_volume': 279, 'last_volume': 0, 'trade_date': 0, 'prevclose': None, 'week_52_high': 0.0, 'week_52_low': 0.0, 'bidsize': 0, 'bidexch': None, 'bid_date': 0, 'asksize': 0, 'askexch': None, 'ask_date': 0}}}
```
They tried BTC and ETH both resulting in the same errors. Cheers.

**Comment by Flame442** [comment]
BTC and ETH are both cryptocurrencies, so I assume that is why it is giving different data than what I expect. That should be handled in a friendlier way though.

**Comment by Flame442** [comment]
This has been fixed on the latest version of the cog. You can update your cogs with `[p]cog update`. Thanks for reporting this!
